CREATE TABLE `terms` (
	`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`title` VARCHAR(100) NOT NULL,
	`body` TEXT NOT NULL,
	`is_optional` BOOLEAN NOT NULL DEFAULT FALSE COMMENT 'TRUE: 선택, FALSE: 필수',
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `store` (
	`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`region_id` BIGINT NOT NULL,
	`category_id` BIGINT NOT NULL,
	`name` VARCHAR(100) NOT NULL,
	`address` VARCHAR(255) NOT NULL,
	`score` DECIMAL(2, 1) NOT NULL DEFAULT 0.0 COMMENT '평점 (반정규화)',
	`latitude` DECIMAL(10, 7) NULL COMMENT '위도',
	`longitude` DECIMAL(10, 7) NULL COMMENT '경도',
	`status` VARCHAR(20) NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN, CLOSED (Soft Delete)',
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `store_owner` (
	`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`member_id` BIGINT NOT NULL,
	`store_id` BIGINT NOT NULL,
	`business_number` VARCHAR(50) NOT NULL COMMENT '사업자등록번호',
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `member_mission` (
	`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`member_id` BIGINT NOT NULL,
	`mission_id` BIGINT NOT NULL,
	`status` VARCHAR(20) NOT NULL DEFAULT 'CHALLENGING' COMMENT 'CHALLENGING, COMPLETE',
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `member_region_clear` (
	`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`member_id` BIGINT NOT NULL,
	`region_id` BIGINT NOT NULL,
	`cleared_count` INT NOT NULL DEFAULT 0,
	`is_rewarded` BOOLEAN NOT NULL DEFAULT FALSE,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `food_category` (
	`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(50) NOT NULL COMMENT '한식, 일식, 중식, 양식, 치킨 등',
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `member` (
	`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(50) NOT NULL,
	`gender` VARCHAR(10) NULL COMMENT 'MALE, FEMALE, NONE',
	`birth_date` DATE NULL,
	`address` VARCHAR(255) NULL,
	`spec_address` VARCHAR(255) NULL,
	`phone_number` VARCHAR(20) NULL,
	`social_type` VARCHAR(20) NOT NULL COMMENT 'KAKAO, NAVER, GOOGLE, APPLE',
	`social_id` VARCHAR(100) NOT NULL COMMENT '소셜 고유 식별자',
	`email` VARCHAR(100) NULL,
	`point` INT NOT NULL DEFAULT 0,
	`status` VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE, INACTIVE',
	`inactive_date` DATETIME NULL COMMENT '탈퇴 및 비활성화 일자 (Soft Delete)',
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `member_prefer` (
	`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`member_id` INT NOT NULL,
	`category_id` INT NOT NULL,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `review` (
	`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`member_id` BIGINT NOT NULL,
	`store_id` BIGINT NOT NULL,
	`score` DECIMAL(2, 1) NOT NULL,
	`body` TEXT NOT NULL,
	`status` VARCHAR(20) NOT NULL DEFAULT 'VISIBLE' COMMENT 'VISIBLE, DELETED (Soft Delete)',
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `region` (
	`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(50) NOT NULL COMMENT '안양시 만안구, 강남구 등',
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `review_image` (
	`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`review_id` BIGINT NOT NULL,
	`image_url` VARCHAR(255) NOT NULL,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `search_history` (
	`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`member_id` BIGINT NOT NULL,
	`keyword` VARCHAR(100) NOT NULL,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `notification` (
	`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`member_id` BIGINT NOT NULL,
	`title` VARCHAR(100) NOT NULL,
	`body` TEXT NOT NULL,
	`is_read` BOOLEAN NOT NULL DEFAULT FALSE,
	`notification_type` VARCHAR(20) NOT NULL COMMENT 'MISSION, REVIEW_REQUEST, EVENT',
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `member_agree` (
	`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`member_id` BIGINT NOT NULL,
	`terms_id` BIGINT NOT NULL,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `mission` (
	`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`store_id` BIGINT NOT NULL,
	`reward` INT NOT NULL COMMENT '지급 포인트',
	`deadline` DATE NOT NULL COMMENT '미션 마감 기한',
	`mission_spec` TEXT NOT NULL COMMENT '미션 달성 조건',
	`status` VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE, INACTIVE (Soft Delete)',
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `point_history` (
	`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`member_id` BIGINT NOT NULL,
	`amount` INT NOT NULL,
	`type` VARCHAR(20) NOT NULL COMMENT 'EARN, USE',
	`description` VARCHAR(100) NOT NULL,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `notification_setting` (
	`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`member_id` BIGINT NOT NULL,
	`is_mission_enabled` BOOLEAN NOT NULL DEFAULT TRUE,
	`is_review_enabled` BOOLEAN NOT NULL DEFAULT TRUE,
	`is_marketing_enabled` BOOLEAN NOT NULL DEFAULT FALSE,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);