import { useMemo, useState } from 'react'
import './styles.css'
import './search.css'
import './bookmark.css'
type Movie={id:number;title:string;original:string;date:string;poster:string;backdrop:string;overview:string;tagline:string;runtime:string}
const movies:Movie[]=[
{id:1,title:'스파이더맨: 브랜드 뉴 데이',original:'Spider-Man: Brand New Day',date:'2026.07.29',poster:'/images/movies/spider-man-brand-new-day.jpg',backdrop:'/images/movies/spider-man-brand-new-day-backdrop.jpg',tagline:'스파이더맨의 새로운 날을 확인하라!',runtime:'2시간 25분',overview:'모두의 기억에서 사라진 피터 파커가 새로운 위협과 마주하며 자신의 정체를 되찾는 이야기입니다.'},
{id:2,title:'스파이더맨: 홈커밍',original:'Spider-Man: Homecoming',date:'2017.07.05',poster:'/images/movies/spider-man-no-way-home.jpg',backdrop:'/images/movies/spider-man-no-way-home-backdrop.jpg',tagline:'어벤져스가 되고 싶은 스파이더맨',runtime:'2시간 13분',overview:'평범한 고등학생 피터 파커가 새로운 능력과 책임을 배워가는 이야기입니다.'},
{id:3,title:'스파이더맨: 노 웨이 홈',original:'Spider-Man: No Way Home',date:'2021.12.15',poster:'/images/movies/spider-man-no-way-home.jpg',backdrop:'/images/movies/spider-man-no-way-home-backdrop.jpg',tagline:'모든 세계가 연결된다',runtime:'2시간 28분',overview:'정체가 밝혀진 피터 파커가 멀티버스의 위협과 맞서 싸웁니다.'},
{id:4,title:'스파이더맨 3',original:'Spider-Man 3',date:'2007.05.01',poster:'/images/movies/spider-man-brand-new-day.jpg',backdrop:'/images/movies/spider-man-brand-new-day-backdrop.jpg',tagline:'새로운 힘, 새로운 적',runtime:'2시간 19분',overview:'피터는 새로운 힘을 얻지만 그 힘은 예상하지 못한 위험을 불러옵니다.'},
{id:5,title:'오디세이',original:'The Odyssey',date:'2026.08.05',poster:'/images/movies/odyssey.jpg',backdrop:'/images/movies/odyssey-backdrop.jpg',tagline:'집으로 돌아가기 위한 긴 여정',runtime:'2시간 30분',overview:'기나긴 여정을 끝내고 고향으로 돌아가기 위한 한 영웅의 모험입니다.'},
{id:6,title:'미니언즈 & 몬스터즈',original:'Minions & Monsters',date:'2026.07.15',poster:'/images/movies/minions-monsters.jpg',backdrop:'/images/movies/minions-monsters-backdrop.jpg',tagline:'작은 친구들의 거대한 모험',runtime:'1시간 35분',overview:'미니언들과 함께 새로운 모험을 떠나는 유쾌한 이야기입니다.'},
{id:7,title:'토이 스토리 5',original:'Toy Story 5',date:'2026.06.17',poster:'/images/movies/toy-story-5.jpg',backdrop:'/images/movies/toy-story-5-backdrop.jpg',tagline:'장난감들의 새로운 모험',runtime:'1시간 45분',overview:'우디와 친구들의 새로운 모험입니다.'},
{id:8,title:'로빈 후드의 죽음',original:'The Death of Robin Hood',date:'2026.06.18',poster:'/images/movies/death-of-robin-hood.jpg',backdrop:'/images/movies/death-of-robin-hood-backdrop.jpg',tagline:'전설의 마지막 이야기',runtime:'2시간 10분',overview:'로빈 후드의 마지막 선택을 그린 이야기입니다.'},
{id:9,title:'이블 데드 번',original:'Evil Dead Burn',date:'2026.07.07',poster:'/images/movies/evil-dead-burn.jpg',backdrop:'/images/movies/evil-dead-burn-backdrop.jpg',tagline:'꺼지지 않는 공포',runtime:'1시간 40분',overview:'불타는 악령과 맞서는 사람들의 이야기입니다.'},
{id:10,title:'옵세션',original:'Obsession',date:'2026.09.02',poster:'/images/movies/obsession.jpg',backdrop:'/images/movies/obsession-backdrop.jpg',tagline:'믿음은 집착으로 변한다',runtime:'1시간 50분',overview:'사랑과 집착 사이에서 벌어지는 심리 스릴러입니다.'}]
const icon=(n:string)=>`/icons/movie-icons/${n}.svg`;const cn=(...v:(string|false|undefined)[])=>v.filter(Boolean).join(' ')
function Header({onSearch}:{onSearch:()=>void}){return <header className="header"><a className="brand" href="/"><img src={icon('movie')}/>UMCine</a><nav><a href="/">영화</a><a href="/search">검색</a><a href="/">내 정보</a></nav><div className="header-actions"><button className="icon-btn" onClick={onSearch}><img src={icon('search')}/></button><button className="login">로그인</button></div></header>}
function SearchBox({value,onChange,onSubmit}:{value:string;onChange:(v:string)=>void;onSubmit:()=>void}){return <form className="search-box" onSubmit={e=>{e.preventDefault();onSubmit()}}><img src={icon('search')}/><input value={value} onChange={e=>onChange(e.target.value)} placeholder="영화 제목을 검색해보세요"/><button type="submit">검색</button></form>}
function Card({movie}:{movie:Movie}){return <a className="card" href={`/movies/${movie.id}`}><img className="poster" src={movie.poster}/><div className="card-info"><h3>{movie.title}</h3><p className="muted">{movie.original}</p><p className="muted">{movie.date}</p><p className="desc">{movie.overview}</p><span className="detail-link">상세 보기 <img src={icon('arrow-right')}/></span></div></a>}
function MovieList(){const [bookmarked,setBookmarked]=useState<number[]>([2,7]);const toggle=(id:number)=>setBookmarked(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id]);return <main className="movie-list"><h1>영화 목록</h1><div className="list-grid">{movies.map(m=><a className="poster-card" key={m.id} href={`/movies/${m.id}`}><div className="poster-wrap"><img src={m.poster} style={{objectFit:'contain',background:'#eceff2'}}/><button className="bookmark-button" type="button" aria-label={bookmarked.includes(m.id)?'북마크 해제':'북마크 추가'} onClick={e=>{e.preventDefault();e.stopPropagation();toggle(m.id)}}><img src={icon(bookmarked.includes(m.id)?'bookmark':'bookmark-outline')}/></button></div><b>{m.title}</b><small>{m.date}</small></a>)}</div></main>}
function SearchPage(){const q=new URLSearchParams(location.search).get('query')||'';const [value,setValue]=useState(q);const result=useMemo(()=>q?movies.filter(m=>`${m.title} ${m.original}`.toLowerCase().includes(q.toLowerCase())):[],[q]);const submit=()=>{location.href=value?`/search?query=${encodeURIComponent(value)}`:'/search'};if(!q)return <main className="search-landing"><h1>어떤 영화를 찾고 있나요?</h1><SearchBox value={value} onChange={setValue} onSubmit={submit}/></main>;return <main className="search-page"><h1>영화 검색</h1><SearchBox value={value} onChange={setValue} onSubmit={submit}/><div className="result-head"><b>'{q}' 검색 결과</b><span>{result.length}개의 영화</span></div>{result.length?<div className="result-grid">{result.map(m=><Card key={m.id} movie={m}/>)}</div>:<p className="notice">검색 결과가 없어요.</p>}</main>}
function Detail({movie}:{movie:Movie|undefined}){if(!movie)return <main className="not-found"><h1>영화를 찾을 수 없어요.</h1><a className="blue-btn" href="/">영화 목록으로</a></main>;return <main className="detail"><section className="hero" style={{backgroundImage:`linear-gradient(90deg,rgba(8,12,18,.9),rgba(8,12,18,.2)),url(${movie.backdrop})`}}><div className="hero-copy"><span className="crumb">영화 목록　›　상세 정보</span><h1>{movie.title}</h1><p>{movie.original}</p><small>{movie.date} · {movie.runtime}</small></div></section><section className="detail-body"><img className="detail-poster" src={movie.poster}/><div className="description"><h2>{movie.tagline}</h2><p>{movie.overview}</p><button className="blue-btn">예매하기</button></div><aside><h3>내 평점</h3><div className="stars">{[1,2,3,4,5].map(i=><img key={i} src={icon('star-outline')}/>)}</div><textarea placeholder="영화에 대한 한줄평을 남겨보세요."/><button className="black-btn">평점 저장</button></aside></section></main>}
export default function App(){const path=location.pathname;const detail=path.match(/^\/movies\/(\d+)/);const page=path==='/search'?<SearchPage/>:detail?<Detail movie={movies.find(m=>m.id===Number(detail[1]))}/>:<MovieList/>;return <><Header onSearch={()=>{location.href='/search'}}/>{page}</>}
