import { Link, useParams } from "@tanstack/react-router";
import BookmarkButton from "../../components/movies/bookmark-button";
import { movies } from "../../data/movies";

export function MovieDetailPage() {
  const { movieId } = useParams({ from: "/movies/$movieId" });
  const movie = movies.find((item) => item.id === Number(movieId));
  if (!movie) return <main className="mx-auto w-[min(1180px,calc(100%-48px))] py-16 text-zinc-600">영화를 찾을 수 없어요.</main>;
  return <main className="pb-20"><section className="relative isolate h-[min(52vw,560px)] min-h-80 overflow-hidden bg-zinc-900"><img src={movie.backdropPath} alt="" aria-hidden="true" className="absolute inset-0 size-full object-cover opacity-60" /><div className="absolute inset-0 bg-linear-to-t from-zinc-950 via-zinc-950/30 to-transparent" /><div className="relative mx-auto flex h-full w-[min(1180px,calc(100%-48px))] items-end pb-12"><div className="max-w-2xl text-white"><p className="text-sm font-medium text-zinc-200">{movie.releaseDate} · {movie.runtime}</p><h1 className="mt-3 text-4xl font-bold tracking-[-1.8px] sm:text-5xl">{movie.title}</h1><p className="mt-2 text-lg text-zinc-300">{movie.originalTitle}</p><div className="mt-5 flex flex-wrap gap-2">{movie.genres.map((genre) => <span key={genre} className="rounded-full border border-white/40 px-3 py-1 text-sm">{genre}</span>)}</div></div></div></section><section className="mx-auto grid w-[min(1180px,calc(100%-48px))] gap-10 pt-12 md:grid-cols-[240px_1fr]"><img src={movie.posterPath} alt={`${movie.title} 포스터`} className="w-full max-w-60 rounded-xl shadow-xl" /><div><Link to="/" className="text-sm font-semibold text-zinc-600 underline underline-offset-4">영화 목록으로</Link><BookmarkButton movieId={movie.id} movieTitle={movie.title} className="ml-4" /><p className="mt-8 text-xl font-bold tracking-[-0.5px] text-zinc-900">{movie.tagline}</p><h2 className="mt-8 text-lg font-bold text-zinc-900">줄거리</h2><p className="mt-3 max-w-2xl leading-8 text-zinc-600">{movie.overview}</p><dl className="mt-9 grid max-w-xl grid-cols-[100px_1fr] gap-y-3 border-t border-zinc-200 pt-6 text-sm"><dt className="font-semibold text-zinc-900">개봉일</dt><dd className="text-zinc-600">{movie.releaseDate}</dd><dt className="font-semibold text-zinc-900">장르</dt><dd className="text-zinc-600">{movie.genres.join(", ")}</dd><dt className="font-semibold text-zinc-900">러닝타임</dt><dd className="text-zinc-600">{movie.runtime}</dd></dl></div></section></main>;
}
