import { Link, useNavigate, useSearch } from "@tanstack/react-router";
import type { SubmitEvent } from "react";
import BookmarkButton from "../../components/movies/bookmark-button";
import { movies } from "../../data/movies";

export function SearchPage() {
  const { query } = useSearch({ from: "/search" });
  const navigate = useNavigate({ from: "/search" });
  const normalizedQuery = query?.trim().toLocaleLowerCase() ?? "";
  const searchResults = normalizedQuery ? movies.filter(({ title, originalTitle }) => title.toLocaleLowerCase().includes(normalizedQuery) || originalTitle.toLocaleLowerCase().includes(normalizedQuery)) : [];
  function handleSubmit(event: SubmitEvent<HTMLFormElement>) { event.preventDefault(); const nextQuery = new FormData(event.currentTarget).get("query")?.toString().trim() ?? ""; navigate({ search: nextQuery ? { query: nextQuery } : {} }); }
  return <main className="mx-auto w-[min(960px,calc(100%-48px))] py-16"><p className="text-xs font-bold tracking-[0.13em] text-zinc-400">SEARCH MOVIES</p><h1 className="mt-2 text-[34px] font-bold tracking-[-1.5px] text-zinc-950">영화 검색</h1><form key={query ?? ""} onSubmit={handleSubmit} className="mt-8 flex gap-2"><input name="query" aria-label="검색어" placeholder="영화 제목을 입력하세요" className="min-w-0 flex-1 rounded-lg border border-zinc-300 px-4 py-3 outline-none transition focus:border-zinc-900 focus:ring-2 focus:ring-zinc-200" defaultValue={query ?? ""} /><button type="submit" className="rounded-lg bg-zinc-900 px-5 py-3 font-semibold text-white transition hover:bg-zinc-700">검색</button></form>{!normalizedQuery ? <p className="mt-10 text-zinc-500">검색어를 입력해 주세요.</p> : <section className="mt-10"><h2 className="text-xl font-bold text-zinc-900">‘{query}’ 검색 결과</h2><p className="mt-2 text-zinc-500">영화 {searchResults.length}편</p>{searchResults.length === 0 ? <p className="mt-8 text-zinc-500">검색 결과가 없어요.</p> : <ul className="mt-6 space-y-5">{searchResults.map((movie) => <li key={movie.id} className="flex gap-4 border-b border-zinc-200 pb-5"><Link to="/movies/$movieId" params={{ movieId: String(movie.id) }} className="shrink-0"><img src={movie.posterPath} alt={`${movie.title} 포스터`} className="h-36 w-24 rounded object-cover" /></Link><div className="min-w-0 flex-1"><Link to="/movies/$movieId" params={{ movieId: String(movie.id) }} className="font-bold text-zinc-900 hover:underline">{movie.title}</Link><p className="mt-1 text-sm text-zinc-500">{movie.originalTitle}</p><p className="mt-2 text-sm text-zinc-600">{movie.releaseDate}</p><p className="mt-2 line-clamp-2 text-sm leading-6 text-zinc-600">{movie.overview}</p><BookmarkButton movieId={movie.id} movieTitle={movie.title} className="mt-4" /></div></li>)}</ul>}</section>}</main>;
}
